### ISSUE TITLE
Skip Login

### ISSUE THREAD

**Issue by Alaskanyoda** [FireAstrox/CS372#10]
You can skip logging in by going to the url of the specified user type.

**Comment by FireAstrox** [comment]
Looking through our user stories and test cases I cannot tell where this is a requirement. While yes this would be an issue for a full website, this is not, and if it's not listed in our requirements and test it shouldn't be of concern or issue. Professor Das never stated this as a requirement, and neither does our documentation, so thank you for your diligent bug report, however since it doesn't pertain to the assignment it will be closed.
